---
image: debian:buster

stages:
  - pages

pages:
  stage: pages
  before_script:
    - apt-get update -qy > /dev/null
    - apt-get install gpg gnupg2 wget -qy
    - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A0546A43624A8331
    - echo "deb http://repo.aptly.info/ squeeze main" >> /etc/apt/sources.list.d/aptly.list
    - apt-get update -qy > /dev/null
    - apt-get install aptly -qy
    - gpg --import --no-tty --batch --yes ${GPG_PRIVATE_KEY}
    - aptly repo create -distribution=xenial -component=main public
    - echo -e "use-agent\npinentry-mode loopback" > ~/.gnupg/gpg.conf
    - echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
  script:
    - mkdir dist/
    - wget https://packagecloud.io/nouchka/home/packages/ubuntu/xenial/dotfiles_0.1.90_amd64.deb/download.deb
    - mv download.deb dist/dotfiles.deb
    - aptly repo add public ./dist/
    - aptly publish repo -batch -passphrase=${GPG_PASSPHRASE} -gpg-key=${GPG_KEY_ID} public
    - mv ~/.aptly/public .
    - gpg --armor --output public/gpg.key --export ${GPG_KEY_ID}
  artifacts:
    paths:
      - public
    when: on_success
    expire_in: 1 year
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
